### ISSUE TITLE
Default bundletool can be updated to the latest 1.8.0

### ISSUE THREAD

**Issue by androideveloper** [bitrise-steplib/bitrise-step-export-universal-apk#16]
Hi. The default bundletool version used in the step is 1.0.0 (published more than 1 year ago), the latest published version is 1.8.0 https://github.com/google/bundletool/releases/tag/1.8.0

Of course, it's possible to change the version to the latest one via param and that is what I did, but would be nice to have the latest version already included by default.

**Comment by ofalvai** [comment]
Hey @androideveloper, thanks for pointing this out, the default version is indeed a bit outdated. Is there any specific new feature in bundletool that you needed when running this step?

**Comment by androideveloper** [comment]
Hi @ofalvai . Nothing specific, but we are migrating to the AGP 7 and it's always good to be on the latest tooling to avoid weird bugs. We had smth similar recently with another library for the build pipeline.
